package H_exception.custom;

public class MainClass {

	public static void main(String[] args) throws Throwable{

		try {
			Aluno aluno = new Aluno("xcv", -1);
			Validar.aluno(aluno);
		} catch (StringVazia e) {
			System.out.println(e.getMessage());
		}
		System.out.println("FIM");
	}

}
